### ISSUE TITLE
Match Problem

### ISSUE THREAD

**Issue by ozanarici** [loungeplease/loungeplease-support#10]
**After MATCH-LOADING Screen**
No matter host or guest, after selecting a flight,(flights selected properly from flight radar) the match loading screen is loaded. For about 5 seconds it is seen and sorry no match(still lorem ipsum) is seen.

**To Reproduce**
1. Go to 'Host select OR Guest Select'
2. Click on 'Airline selection and select KLM'
3. Entrr code for KLM 683
4. Host is on loading screen and guest is after making properly payment on loading screen. But no match. (to be on the same seconds for loading host also waited for the guest to enter credit card details)

**Expected behavior**
5 seconds loading screen is too short to find a match. The screen should be maybe 10 seconds and we must be sure that if a match is nearby there should be a match

**Actual behavior**
Sorry no match screens are seen and the loading was also so short.

**Screenshots**
![img-20180813-wa0006](https://user-images.githubusercontent.com/42268853/44028404-6db4e3be-9f02-11e8-922f-fb7a7d64a373.jpg)
![img-20180813-wa0005](https://user-images.githubusercontent.com/42268853/44028418-77e992ee-9f02-11e8-943c-164df7236053.jpg)
![img-20180813-wa0004](https://user-images.githubusercontent.com/42268853/44028423-7f6fd5aa-9f02-11e8-8601-50d2a860b080.jpg)

**Environment (please complete the following information):**
 - APK loungeplease-mobile 2018-08-13 12-43-00.apk

**Additional context**

**Comment by hasancansaral** [comment]
Resolved.

**Comment by hasancansaral** [comment]
Resolved.
