### ISSUE TITLE
Match Algorithm Issue

### ISSUE THREAD

**Issue by aucuncu** [loungeplease/loungeplease-support#11]
**Describe the bug**
In the profile information I choose Miles&Smiles Elite membership. After that I tried to get a match by choosing myself as a host on Delta Airlines. Although I am a gold member on Star Alliance I am just a regular passenger on Delta Airlines so I shouldnt choose myself as a host.

**To Reproduce**
1. Go to profile tab and than choose your loyalty program as Miles&Smiles Elite.
2. go back and choose yourself as a host and enter the flight number dl46 (Delta Airlines)
3. Click on match button and wait for a guest.
4. Loading screen comes and look for a match.

**Expected behavior**
it should show a error notification like 'you can not have guest or there is no available lounge etc.'

**Actual behavior**
If there is a guest the system automatically gets a match.

**Screenshots**
Since we were doing this together we couldn't get a screenshot and we cannot reproduce it now.

**Environment (please complete the following information):**
 - android: [usb installed version 08.15]

**Additional context**

**Comment by hasancansaral** [comment]
Host'un loyalty programının havayolunun alliance'ının, yine host'un uçtuğu havayolunun alliance'ı ile aynı olması gerekiyor değil mi? Kural tam olarak bu mudur?

**Comment by hasancansaral** [comment]
Resolved.
