### ISSUE TITLE
Match Problem

### ISSUE THREAD

**Issue by aucuncu** [loungeplease/loungeplease-support#13]
**Describe the bug**
I choose myself as a  host and and my status on my profile is elite plus. I became host and try to get a match. I tried to pick up a guest for Lufthansa 1182 and it didn't work out.

**To Reproduce**
1. Go to host page and choose your airline as Lufthansa and enter your flight number as 1182
2. Click on submit to find someone button.

**Expected behavior**
The should start to run and try to find a match.

**Actual behavior**
We just received the 'no lounge available bug'

**Screenshots**
![whatsapp image 2018-08-16 at 20 05 24](https://user-images.githubusercontent.com/42220305/44262547-16369b80-a224-11e8-9224-ca8f5ec43300.jpeg)
![whatsapp image 2018-08-16 at 20 05 24-2](https://user-images.githubusercontent.com/42220305/44262551-19ca2280-a224-11e8-886b-2f009aa56310.jpeg)

**Environment (please complete the following information):**
 - OS: [e.g. iOS16.08]
 

**Additional context**

**Comment by hasancansaral** [comment]
Resolved.
