### ISSUE TITLE
Match Problem -no lounge available-

### ISSUE THREAD

**Issue by aucuncu** [loungeplease/loungeplease-support#14]
**Describe the bug**
When I try to look for a host from schipol airport I get an error message. I enter my flight number - AF8399-  and submit my request I get this no lounge available message.

**To Reproduce**
1. Go to host tab and enter your flight number - my flight was Air France 8399 and I tried this on 17.08 at 06.57 ny time.
2. Click on submit to find someone.
3. You will receive the no lounge available error.

**Expected behavior**
It should start to run and look for a proper match.

**Actual behavior**
Nothing happens and just gives the error page

**Screenshots**
![whatsapp image 2018-08-17 at 06 53 21](https://user-images.githubusercontent.com/42220305/44262974-bccf6c00-a225-11e8-91dc-699f768431b1.jpeg)

**Environment (please complete the following information):**
 - Version: [android 16.08 release]

**Additional context**

**Comment by hasancansaral** [comment]
Resolved.
