### ISSUE TITLE
Match Problem

### ISSUE THREAD

**Issue by aucuncu** [loungeplease/loungeplease-support#15]
**Describe the bug**
I choose myself as a host and try to get someone into a lounge from schipol. but I couldn't manage to get a match.

**To Reproduce**
1. Go to host tab 
2. Choose your airline as Qatar and flight number 274.(time was 07.03 ny time)
3. Click submit to find a match button.

**Expected behavior**
I changed my status to Qatar gold in order to get a match and it should look for a guest since I am eligible.

**Actual behavior**
the app didn't search for a guest.

**Screenshots**
![whatsapp image 2018-08-17 at 07 03 44](https://user-images.githubusercontent.com/42220305/44263351-43d11400-a227-11e8-959c-30d7de1ac8bf.jpeg)

**Environment (please complete the following information):**
 - Version: [android 16.08 release]

**Additional context**

**Comment by hasancansaral** [comment]
Resolved.
