### ISSUE TITLE
App Screen Fitting Problem

### ISSUE THREAD

**Issue by aucuncu** [loungeplease/loungeplease-support#16]
**Describe the bug**
When we enter the app by using iPhone 6s plus , it looks like that the app doesn't fit to the screen.

**To Reproduce**
1. Open the app by using facebook login. (Our device was iPhone 6s plus)
2. Click on facebook login button.
3. Go to profile information page.

**Expected behavior**
The app should fit the screen perfectly

**Actual behavior**
It doesn't fit and there is a small gap on the right side of the app

**Screenshots**
![whatsapp image 2018-08-16 at 20 05 03](https://user-images.githubusercontent.com/42220305/44263643-5dbf2680-a228-11e8-8053-d4f7945181e0.jpeg)

**Environment (please complete the following information):**
 - OS: [e.g. iOS16.08]

**Additional context**

**Comment by aucuncu** [comment]
Selam,
Nornal sign in yapildiginda da ayni durum olmakta. Belirtilen cihazda gerceklesmekte bu durum.

**Comment by hasancansaral** [comment]
Resolved.
