### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by hasancansaral** [loungeplease/loungeplease-support#2]
**Describe the bug**
When you select “Forgot password” from the login screen.

**To Reproduce**
1. Select Login 
2. Select forgot password
3. Fill in your email address
4. Go to your email and check if you receive a password reset link

**Expected behavior**
When you hit “Forgot Password” from the login page, an email should be sent from LP with a password reset link that will allow you to successfully change your password.

**Actual behavior**
“Forgot password” does not work. You never receive an email with the password reset link.

**Screenshots**
![3](https://user-images.githubusercontent.com/704385/43949597-a99a7772-9c96-11e8-8f69-c827ef2e111f.jpg)

**Environment (please complete the following information):**
 - OS: Android
 - Version: loungeplease-mobile 2018-08-06 16-44-00.apk

**Comment by hasancansaral** [comment]
Cannot replicate, password reset emails are being sent in `loungeplease-mobile 2018-08-06 16-44-00.apk`.

**Comment by hasancansaral** [comment]
@bariskayadelen e-mail sunucusu 554 5.1.8 Sender Address Blocked hatasi veriyor. Bunu Zoho'dan cozmemiz lazim. [Ref #1 ](https://help.zoho.com/portal/community/topic/sending-failed-reason-554-5-1-8-sender-address-blocked-25-10-2010), [Ref #2](2). Adamlarla irtibata gecmek gerekebilir, konu sizde.

**Comment by bariskayadelen** [comment]
I check the account that we we sent email. System has blocked our account. 
I've send an email to  support@zohomail.com and have been waiting news.

**Comment by hasancansaral** [comment]
Resolved.
