### ISSUE TITLE
Payment Problem

### ISSUE THREAD

**Issue by aucuncu** [loungeplease/loungeplease-support#7]
**Describe the bug**
So i choose myself as a guest and looking for a host. The app wants me to enter my payment information and when i enter my credit card information the screen just frozen and the uploading bar keep running forelock 2 minutes and nothing happens.

**To Reproduce**
1. Choose yourself as a host on the app
2. Type your flight information - i choose lh 918  (time was 18:17)-
3. Click submit to find someone button
4. When you get the payment page choose stripe and enter the credit card info-i used test card info-
5. Click pay button and then you will see the waiting bar and it doesn't proceed.
**Expected behavior**
It should just accept the payment and move to the next screen.

**Actual behavior**
It didn't accept the payment and looked like trying to get the payment but nothing happened.

**Screenshots**
![whatsapp image 2018-08-10 at 18 21 31](https://user-images.githubusercontent.com/42220305/43969085-ba013e30-9cd1-11e8-94cd-e80a3724f964.jpeg)

**Environment (please complete the following information):**
 - Android: [08.10.2018 version]

**Additional context**

**Comment by hasancansaral** [comment]
Resolved, .apk file available on Drive and iOS will be deployed tonight.
