### ISSUE TITLE
Phone Number Input

### ISSUE THREAD

**Issue by SabineZureikat** [loungeplease/loungeplease-support#9]
**Describe the bug**
When you want to fill in your phone number, the (+) sign appears only when you start typing in the numbers. So as I was typing in my number with country code, I ended up with +00, becuase I didn't know the (+) sign would appear. It would be great if the (+) sign is always there and doesn't only appear when I start typing in my number.

**To Reproduce**
1. Go to signup or your profile page
2. Click on the phone number tab and start typing in your number
3. Notice that the (+) sign only appears when you start writing.

**Expected behavior**
Having the plus sign visible from the start, so I wouldn't end up inputting (+) and 00 together.

**Actual behavior**
(+) sign appears only when you start typing.

**Screenshots**

![38877010_273820836546031_8610258196856045568_n](https://user-images.githubusercontent.com/42295841/43991714-99d70072-9d7b-11e8-86a2-f0de6bfdd107.jpg)

![38923513_1796276050454926_7484426064597352448_n](https://user-images.githubusercontent.com/42295841/43991715-99f6db4a-9d7b-11e8-9991-80e1d9101786.jpg)

**Environment (please complete the following information):**
- IOS
- loungeplease-mobile.ipa (06/08/2018)

**Additional context**
None

**Comment by hasancansaral** [comment]
Made some improvements to phone input. Although it is not possible to 100% achieve what you are asking for (since it's not only dependent on us but also the platform we use - Ionic), it is now better. This is probably the best we can achieve for the moment being. Closing as resolved.
